-- Run on a NEW Supabase project. Never expose a service-role key to the browser.
create extension if not exists pgcrypto;
create type public.user_role as enum ('candidate','recruiter','admin');
create type public.job_status as enum ('draft','open','closed');
create type public.application_status as enum ('applied','reviewed','shortlisted','interview','selected','rejected');
create table public.profiles(id uuid primary key references auth.users(id) on delete cascade,full_name text not null,email text not null,role public.user_role not null default 'candidate',phone text,location text,headline text,bio text,profile_photo_path text,resume_path text,intro_video_path text,created_at timestamptz default now(),updated_at timestamptz default now());
create table public.companies(id uuid primary key default gen_random_uuid(),recruiter_id uuid unique not null references public.profiles(id) on delete cascade,company_name text not null,logo_path text,description text,website text,industry text,location text,created_at timestamptz default now(),updated_at timestamptz default now());
create table public.skills(id uuid primary key default gen_random_uuid(),name text unique not null,category text);
create table public.candidate_skills(candidate_id uuid references public.profiles(id) on delete cascade,skill_id uuid references public.skills(id) on delete cascade,primary key(candidate_id,skill_id));
create table public.projects(id uuid primary key default gen_random_uuid(),candidate_id uuid references public.profiles(id) on delete cascade,title text not null,description text,github_url text,live_url text,created_at timestamptz default now());
create table public.portfolio_links(id uuid primary key default gen_random_uuid(),profile_id uuid references public.profiles(id) on delete cascade,platform text check(platform in('youtube','instagram','github','linkedin','website')),url text not null,unique(profile_id,platform));
create table public.jobs(id uuid primary key default gen_random_uuid(),company_id uuid not null references public.companies(id) on delete cascade,recruiter_id uuid not null references public.profiles(id) on delete cascade,title text not null,description text not null,department text,location text,employment_type text,experience_min int,experience_max int,salary_min numeric,salary_max numeric,status public.job_status default 'draft',created_at timestamptz default now(),updated_at timestamptz default now());
create table public.applications(id uuid primary key default gen_random_uuid(),job_id uuid references public.jobs(id) on delete cascade,candidate_id uuid references public.profiles(id) on delete cascade,status public.application_status default 'applied',resume_path text,cover_letter text,created_at timestamptz default now(),updated_at timestamptz default now(),unique(job_id,candidate_id));
create index jobs_status_created on public.jobs(status,created_at desc);create index jobs_recruiter on public.jobs(recruiter_id);create index apps_candidate on public.applications(candidate_id,created_at desc);create index apps_job on public.applications(job_id,created_at desc);create index candidate_skill on public.candidate_skills(skill_id);
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$declare r text;begin r:=coalesce(new.raw_user_meta_data->>'role','candidate');if r not in('candidate','recruiter') then r:='candidate';end if;insert into public.profiles(id,full_name,email,role) values(new.id,coalesce(nullif(new.raw_user_meta_data->>'full_name',''),split_part(new.email,'@',1)),new.email,r::public.user_role) on conflict(id) do nothing;return new;end;$$;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();
create or replace function public.touch() returns trigger language plpgsql as $$begin new.updated_at=now();return new;end;$$;
create trigger profiles_touch before update on public.profiles for each row execute function public.touch();create trigger companies_touch before update on public.companies for each row execute function public.touch();create trigger jobs_touch before update on public.jobs for each row execute function public.touch();create trigger applications_touch before update on public.applications for each row execute function public.touch();
-- RLS
alter table public.profiles enable row level security;alter table public.companies enable row level security;alter table public.skills enable row level security;alter table public.candidate_skills enable row level security;alter table public.projects enable row level security;alter table public.portfolio_links enable row level security;alter table public.jobs enable row level security;alter table public.applications enable row level security;
create policy profiles_select_own on public.profiles for select to authenticated using(id=auth.uid());create policy profiles_update_own on public.profiles for update to authenticated using(id=auth.uid()) with check(id=auth.uid());
create policy companies_read on public.companies for select to authenticated using(true);create policy companies_insert on public.companies for insert to authenticated with check(recruiter_id=auth.uid());create policy companies_update on public.companies for update to authenticated using(recruiter_id=auth.uid()) with check(recruiter_id=auth.uid());create policy companies_delete on public.companies for delete to authenticated using(recruiter_id=auth.uid());
create policy skills_read on public.skills for select to authenticated using(true);
create policy cs_read on public.candidate_skills for select to authenticated using(true);create policy cs_insert on public.candidate_skills for insert to authenticated with check(candidate_id=auth.uid());create policy cs_delete on public.candidate_skills for delete to authenticated using(candidate_id=auth.uid());
create policy projects_read on public.projects for select to authenticated using(true);create policy projects_insert on public.projects for insert to authenticated with check(candidate_id=auth.uid());create policy projects_update on public.projects for update to authenticated using(candidate_id=auth.uid()) with check(candidate_id=auth.uid());create policy projects_delete on public.projects for delete to authenticated using(candidate_id=auth.uid());
create policy portfolio_read on public.portfolio_links for select to authenticated using(true);create policy portfolio_insert on public.portfolio_links for insert to authenticated with check(profile_id=auth.uid());create policy portfolio_update on public.portfolio_links for update to authenticated using(profile_id=auth.uid()) with check(profile_id=auth.uid());create policy portfolio_delete on public.portfolio_links for delete to authenticated using(profile_id=auth.uid());
create policy jobs_read on public.jobs for select to authenticated using(status='open' or recruiter_id=auth.uid());create policy jobs_insert on public.jobs for insert to authenticated with check(recruiter_id=auth.uid());create policy jobs_update on public.jobs for update to authenticated using(recruiter_id=auth.uid()) with check(recruiter_id=auth.uid());create policy jobs_delete on public.jobs for delete to authenticated using(recruiter_id=auth.uid());
create policy apps_read on public.applications for select to authenticated using(candidate_id=auth.uid() or exists(select 1 from public.jobs j where j.id=applications.job_id and j.recruiter_id=auth.uid()));create policy apps_insert on public.applications for insert to authenticated with check(candidate_id=auth.uid() and exists(select 1 from public.jobs j where j.id=applications.job_id and j.status='open'));create policy apps_update on public.applications for update to authenticated using(exists(select 1 from public.jobs j where j.id=applications.job_id and j.recruiter_id=auth.uid())) with check(exists(select 1 from public.jobs j where j.id=applications.job_id and j.recruiter_id=auth.uid()));
insert into public.skills(name,category) values('Sales','Business'),('HR','People'),('IT','Technology'),('Marketing','Business'),('Finance','Business'),('Design','Creative'),('Customer Support','Operations'),('Data Analytics','Technology') on conflict(name) do nothing;
-- Storage buckets
insert into storage.buckets(id,name,public) values('profile-pics','profile-pics',true),('company-logos','company-logos',true),('resumes','resumes',false),('intro-videos','intro-videos',false) on conflict(id) do nothing;
create policy profile_pics_read on storage.objects for select using(bucket_id='profile-pics');create policy profile_pics_write on storage.objects for insert to authenticated with check(bucket_id='profile-pics' and (storage.foldername(name))[1]=auth.uid()::text);
create policy resumes_write on storage.objects for insert to authenticated with check(bucket_id='resumes' and (storage.foldername(name))[1]=auth.uid()::text);create policy resumes_read_own on storage.objects for select to authenticated using(bucket_id='resumes' and (storage.foldername(name))[1]=auth.uid()::text);create policy resumes_delete_own on storage.objects for delete to authenticated using(bucket_id='resumes' and (storage.foldername(name))[1]=auth.uid()::text);
create policy videos_write on storage.objects for insert to authenticated with check(bucket_id='intro-videos' and (storage.foldername(name))[1]=auth.uid()::text);create policy videos_read_own on storage.objects for select to authenticated using(bucket_id='intro-videos' and (storage.foldername(name))[1]=auth.uid()::text);create policy videos_delete_own on storage.objects for delete to authenticated using(bucket_id='intro-videos' and (storage.foldername(name))[1]=auth.uid()::text);

-- Public candidate view: exposes only non-sensitive profile fields. Never exposes email, phone, resume path or private video path.
create or replace view public.candidate_public_profiles as
select id, full_name, headline, location, bio, profile_photo_path
from public.profiles where role='candidate';

-- Recruiters may read a candidate resume only when that candidate has applied to one of their jobs.
create policy resumes_read_authorized_recruiter on storage.objects
for select to authenticated
using (bucket_id='resumes' and exists (
  select 1 from public.applications a
  join public.jobs j on j.id=a.job_id
  where a.candidate_id::text=(storage.foldername(name))[1]
    and a.candidate_id::text=(storage.foldername(name))[1]
    and j.recruiter_id=auth.uid()
));
